Cluster/Cluster/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView


admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url('', include('users.urls', namespace='users')),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT
    }),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT
    }),

)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

Cluster/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import (
    ProfileUpdateView,
    ProfileView,
    FollowingListView,
    FollowerListView,
    LaundingPageView,
    DashboardView)


urlpatterns = patterns('',
    url(r'^$', DashboardView.as_view(), name='home'),
    url(r'^profile/(?P<user_name>\w+)/$', ProfileView.as_view(), name='profile'),
    url(r'^following/(?P<user_name>\w+)/$', FollowingListView.as_view(), name='following'),
    url(r'^follower/(?P<user_name>\w+)/$', FollowerListView.as_view(), name='follower'),
    url(r'^settings/profile/$', ProfileUpdateView.as_view(), name='settings'),
    url(r'^launding/$', LaundingPageView.as_view(), name="launding"),
)

Cluster/community/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


class Game(models.Model):
    name = models.CharField(_('name'), max_length=20)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(_('created'), auto_now=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(_('name'), max_length=12)
    created = models.DateTimeField(_('created'), auto_now=True)
    updated = models.DateTimeField(_('updated'), auto_now_add=True)

    def __str__(self):
        return self.name


class Community(models.Model):
    game = models.ForeignKey(Game)
    name = models.CharField(_('name'), max_length=20)
    description = models.TextField(_('description'))

    def __str__(self):
        return self.name


class Thread(models.Model):
    community = models.ForeignKey(Community)
    name = models.CharField(_('name'), max_length=20)
    user = models.ForeignKey(User)
    value = models.TextField(_('text vallue'))
    created = models.DateTimeField(_('created'), auto_now=True)
    updated = models.DateTimeField(_('updated'), auto_now=True)

    def __str__(self):
        return self.name

Cluster/users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from .manager import FollowManager
from model_utils.models import TimeStampedModel
from django.db.models.signals import post_save


class Picture(TimeStampedModel):
    """
    Simple Picture
    """
    user = models.ForeignKey(User)
    picture = models.ImageField(
        upload_to="images/",
        default='/images/thumbnails/anonymous.png')

    def __str__(self):
        return str(self.picture)


class Profile(TimeStampedModel):
    """
    プロフィール
    """
    name = models.CharField(_('accounts name'), max_length=24)
    user = models.OneToOneField(User)
    thumbnail = models.ForeignKey(Picture)
    homepage = models.URLField(_('homepage'), blank=True)
    self_introduction = models.TextField(_('self introduction'), blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        picture = Picture.objects.create(user=self.user)
        picture.save()
        self.name = self.user.username
        self.thumbnail = picture
        super(Profile, self).save(*args, **kwargs)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = Profile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)


User.profile = property(lambda u: Profile.objects.get_or_create(user=u)[0])


class Follow(TimeStampedModel):
    """
    フォローモデル
    """
    from_user = models.ForeignKey(User)
    target_user = models.ForeignKey(User, related_name='followed_by')
    is_active = models.BooleanField(default=True)
    objects = FollowManager()

    def __str__(self):
        return '%s is following %s.' % (
            self.from_user.username, self.target_user.username)

Cluster/community/views.py
from django.shortcuts import render

# Create your views here.

Cluster/users/views.py
# -*- coding: utf-8 -*-
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, ListView, CreateView, TemplateView
from django.views.generic.edit import UpdateView, FormView
from django.contrib.auth.models import User
from .models import Profile, Follow


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'


class FollowingListView(ListView):
    template_name = 'users/views/following.html'
    slug_field = 'name'
    slug_url_kwarg = 'user_name'
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs['user_name'])
        self.object = user.profile
        return super(FollowingListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FollowingListView, self).get_context_data(**kwargs)
        context['target_user'] = self.object.user
        return context

    def get_queryset(self):
        return Follow.objects.get_following(self.object.user, count=5)


class FollowerListView(ListView):
    template_name = 'users/views/follower.html'
    slug_url_kwarg = 'user_name'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(User, username=self.kwargs['user_name'])
        return super(FollowerListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FollowerListView, self).get_context_data(**kwargs)
        context['login_user'] = self.request.user
        context['target_user'] = get_object_or_404(User, username=self.kwargs['user_name'])
        return context

    def get_queryset(self):
        return Follow.objects.get_follower(self.object, count=20)


class ProfileView(DetailView):
    model = Profile
    slug_url_kwarg = 'user_name'
    template_name = 'users/views/profile.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User, username=self.kwargs['user_name'])

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        followers = Follow.objects.get_follower(self.object, count=5)
        context['followers'] = followers
        followings = Follow.objects.get_following(self.object)
        context['followings'] = followings
        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['name', 'thumbnail', 'homepage', 'self_introduction']
    template_name = 'users/views/edit_profile.html'
    success_url = 'home'

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)

    def dispatch(self, *args, **kwargs):
        return super(ProfileUpdateView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse(self.success_url)

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['user'] = self.object.user
        return context


class LaundingPageView(TemplateView):
   template_name = "users/views/launding_page.html"

Cluster/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} Cluster {% endblock title %} - Cluster</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to project.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>


  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'users:home' %}">Cluster</a>
          </div>
          <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="">お気に入り</a></li>

                  {% if user.is_authenticated %}
                      <li><a href="{% url 'users:settings' %}">
                          <img src="{{ MEDIA_URL }}{{ user.profile.thumbnail }}" width="30px" height="30px"/>
                      </a></li>
                  {% else %}
                      <li><a href="{% url 'account_email' %}">ログイン</a></li>
                      <li><a href="{% url 'account_signup' %}">アカウント登録</a></li>
                  {% endif %}
              </ul>
          </div><!--/.nav-collapse -->
      </div>
  </div>

  <div class="container">

      {% block content %}
          <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
  </div><!-- /.container -->


  <!-- Le javascript
  ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% load static %}
    <script type="text/javascript" src='{% static 'jquery/jquery.js' %}'></script>
    <script type="text/javascript" src='{% static 'bootstrap/dist/js/bootstrap.min.js' %}'></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>

Cluster/templates/home.html
{% extends 'base.html' %}

{% block title %}ダッシュボード{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}ダッシュボード{% endblock %}

{% block content %}
    最近流行のゲーム
    ウォッチ中のゲーム


{% endblock %}

{% block extra_js %}

{% endblock %}

Cluster/templates/partial/_follower_thumbnails.html
<ul>
    {% for follow in followings %}
        <li><a href="{% url 'users:profile' follow.target_user.username %}">
            <img src="{{ MEDIA_URL }}{{ follow.target_user.profile.thumbnail }}" width="50" height="50" />
        </a></li>
    {% endfor %}
</ul>

Cluster/templates/partial/_following_thumbnails.html
{% for follower in followers %}
    <li><a href="{% url 'users:profile' follower.from_user.username  %}">
        <img src="{{ MEDIA_URL }}{{ follower.from_user.profile.thumbnail }}" width="50" height="50"/>
    </a></li>
{% endfor %}

Cluster/templates/users/base_user.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}{% endblock %}

{% block content %}
    {% include 'partial/_users_header.html' %}
    {% block user_content %}
    {% endblock user_content %}
    {% include 'partial/_users_footer.html' %}
{% endblock %}

{% block extra_js %}

{% endblock %}

Cluster/templates/users/views/edit_profile.html
{% extends 'users/base_user.html' %}

{% block title %}プロフィール設定{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}プロフィール設定{% endblock %}

{% block content %}
    {% if form.has_errors %}
        <p>指定されたユーザ名は使用できません</p>
    {% endif %}
    <form action="{% url 'users:settings' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
{#        <ul>#}
{#            <li>ユーザ名: {{ form.name }}</li>#}
{#            <li>サムネイル画像: {{ form.thumbnail }}</li>#}
{#            <li>サイト/ブログ: {{ form.homepage }}</li>#}
{#            <li>自己紹介: {{ form.self_introduction }}</li>#}
{#        </ul>#}
        <input type="submit" value="プロフィールを更新">
    </form>
{% endblock %}

{% block extra_js %}

{% endblock %}

Cluster/templates/users/views/follower.html
{% extends 'users/base_user.html' %}

{% block title %}
    {{ target_user.profile.name }}さんをフォローしているユーザ
{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}
    {{ target_user.profile.name }}さんをフォローしているユーザ
{% endblock %}

{% block content %}
    <div class="wrapper">
        <p>フォロワー:{{ object_list|length }}人</p>
        {% for follow in object_list %}
            <li><a href="{% url 'users:profile' follow.from_user.username  %}">
                <img src="{{ MEDIA_URL }}{{ follow.from_user.profile.thumbnail }}" width="50" height="50" /></a>
                <p>{{ follow.from_user.profile.name }}</p>
                <p>自己紹介</p>
                <p>{{ follow.from_user.profile.self_introduction|default:"なし" }}</p>
            </li>
        {% endfor %}
    </div>
{% endblock %}

{% block extra_js %}
{% endblock %}

Cluster/templates/users/views/following.html
{% extends 'users/base_user.html' %}

{% block title %}
  {{ target_user.profile.name }} さんのフォロー中のユーザー
{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}
  {{ target_user.profile.name }} さんのフォロー中のユーザー
{% endblock %}

{% block content %}
  <div class="wrapper">
      <p>{{ object_list|length }}人</p>
      {% for follow in object_list %}
            <li><a href="{% url 'users:profile' follow.target_user.username  %}">
                <img src="{{ MEDIA_URL }}{{ follow.target_user.profile.thumbnail }}" width="50" height="50" />
                {{ follow.target_user.profile.name }}
                {{ follow.target_user.profile.self_introduction }}
            </a></li>
      {% endfor %}
  </div>
  {% endblock %}

{% block extra_js %}
{% endblock %}

Cluster/templates/users/views/launding_page.html
{% extends 'base.html' %}

{% block title %}ラウンディングページ{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}ラウンディングページ{% endblock %}

{% block content %}
    <a href="{% url 'account_signup' %}"><p>登録</p></a>
{% endblock %}

{% block extra_js %}

{% endblock %}

Cluster/templates/users/views/profile.html
{% extends 'users/base_user.html' %}

{% block title %}
  {{ object.profile.name }} - Cluster
{% endblock %}

{% block extra_css %}{% endblock %}

{% block page_title %}
    {{ object.profile.name }} さんのプロフィール
{% endblock %}

{% block content %}
  <div class="wrapper">
    <div class="left-menu">
      <h2>ユーザ名</h2>
      <p>{{ object.profile.name }}</p>
      <img src="{{ MEDIA_URL }}{{ object.profile.thumbnail }}" width="300" height="300" />

      {% if object.profile.homepage %}
     <h2>ホームページ</h2>
     <p>{{ object.profile.homepage }}</p>
      {% endif %}

      <h2>自己紹介</h2>
      <p>{{ object.profile.self_introduction }}</p>

      {% if user == object %}
          <p><a href="{% url 'users:settings' %}">プロフィールを編集する</a></p>
      {% endif %}

      <h2>フォロー</h2>
      <p>{{ followings|length }} 人</p>
        {% include 'partial/_follower_thumbnails.html' with followings=followings %}

      <h2>フォロワー</h2>
      <p>{{ followers|length }} 人</p>
        {% include 'partial/_following_thumbnails.html' with follower=follower %}
    </div>
  </div>
  {% endblock %}
{% block extra_js %}
{% endblock %}